[package]
productName = "spotify-downloader-gui"
version = "0.0.1"

[tauri.bundle]
active = true
category = "Music"
copyright = ""
externalBin = []
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico"
]
identifier = "gui.spotdl.app"
longDescription = "GUI app for spotDL"
shortDescription = "GUI app for spotDL"
resources = []
targets = "all"

[tauri.bundle.deb]
depends = [ ]

[tauri.bundle.macOS]
exceptionDomain = ""
frameworks = [ ]

[tauri.bundle.windows]
digestAlgorithm = "sha256"
timestampUrl = ""

[tauri.updater]
active = false
