[package]
product-name = "spotify-downloader-gui"
version = "0.0.1"

[tauri.allowlist]
all = false

[tauri.allowlist.dialog]
confirm = true

[tauri.allowlist.shell]
open = "\\S+"

[tauri.bundle]
active = true
category = "Music"
copyright = ""
external-bin = []
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico"
]
identifier = "gui.spotdl.app"
long-description = "GUI app for spotDL"
short-description = "GUI app for spotDL"
resources = []
targets = "all"

[tauri.bundle.deb]
depends = []

[tauri.bundle.macOS]
exception-domain = ""
frameworks = []
entitlements = ""
provider-short-name = ""
signing-identity = ""

[tauri.bundle.windows]
digest-algorithm = "sha256"
timestamp-url = ""
certificate-thumbprint = ""

[tauri.security]
csp = ""

[tauri.updater]
active = false

[build]
dist-dir = "app-ui/build"
dev-path = "http://localhost:5173"
with-global-tauri = true